#!/bin/bash
# Apache Tomcat 10.1.28 setup script for Ubuntu (2025)
set -e

sudo apt update -y
sudo apt install -y openjdk-17-jdk wget

java -version

wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.28/bin/apache-tomcat-10.1.28.tar.gz
tar -zxvf apache-tomcat-10.1.28.tar.gz

sed -i '56  a\<role rolename="manager-gui"/>' apache-tomcat-10.1.28/conf/tomcat-users.xml
sed -i '57  a\<role rolename="manager-script"/>' apache-tomcat-10.1.28/conf/tomcat-users.xml
sed -i '58  a\<user username="tomcat" password="admin@123" roles="manager-gui,manager-script"/>' apache-tomcat-10.1.28/conf/tomcat-users.xml
sed -i '59  a\</tomcat-users>' apache-tomcat-10.1.28/conf/tomcat-users.xml
sed -i '56d' apache-tomcat-10.1.28/conf/tomcat-users.xml

sed -i '21d' apache-tomcat-10.1.28/webapps/manager/META-INF/context.xml
sed -i '22d' apache-tomcat-10.1.28/webapps/manager/META-INF/context.xml

sh apache-tomcat-10.
